### ISSUE TITLE
Make types fails

### ISSUE THREAD

**Issue by noleti** [neherlab/covid19_scenarios#590]
# 🐛 Bug Report

- `make types` fails, while it worked a couple of days ago on my machine 

## How to reproduce

Steps to reproduce the issue:

 1. `cd data` 
 2. `make types`
 3. observe failure

## 😯 Current Behavior

```
$ make types
rm -rf generated/**
cd .. && yarn install && yarn schema:totypes
yarn install v1.22.4
[1/4] Resolving packages...
warning Resolution field "core-js@3.6.4" is incompatible with requested version "core-js@^2.4.1"
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > bootstrap@4.4.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.4.1" has unmet peer dependency "popper.js@^1.16.0".
warning " > connected-react-router@6.8.0" has unmet peer dependency "seamless-immutable@^7.1.3".
warning " > react-dates@21.8.0" has unmet peer dependency "react-with-direction@^1.3.1".
warning " > eslint-config-airbnb@18.1.0" has incorrect peer dependency "eslint-plugin-react-hooks@^2.5.0 || ^1.7.0".
warning " > eslint-config-react-app@5.2.1" has incorrect peer dependency "eslint-plugin-react-hooks@1.x || 2.x".
warning " > fast-sass-loader@1.5.0" has incorrect peer dependency "node-sass@4.x || 3.x".
warning "stylelint-config-primer > stylelint-order@2.2.1" has incorrect peer dependency "stylelint@^9.10.1 || ^10.0.0".
warning " > stylelint-no-indistinguishable-colors@1.3.0" has incorrect peer dependency "stylelint@^11.1.1".
warning " > tslint-config-airbnb@5.11.2" has incorrect peer dependency "tslint@^5.11.0".
warning " > tslint-consistent-codestyle@1.16.0" has incorrect peer dependency "tslint@^5.0.0".
warning " > tslint-eslint-rules@5.4.0" has incorrect peer dependency "tslint@^5.0.0".
warning "tslint-config-airbnb > tslint-microsoft-contrib@5.2.1" has incorrect peer dependency "tslint@^5.1.0".
warning "tslint-config-airbnb > tslint-consistent-codestyle > @fimbul/bifrost@0.21.0" has incorrect peer dependency "tslint@^5.0.0".
warning " > tslint-microsoft-contrib@6.2.0" has incorrect peer dependency "tslint@^5.1.0".
warning " > tslint-react@4.2.0" has incorrect peer dependency "tslint@^5.1.0".
warning " > tslint-sonarts@1.9.0" has incorrect peer dependency "tslint@^5.11.0".
[4/4] Building fresh packages...
warning Ignored scripts due to flag.
Done in 27.50s.
yarn run v1.22.4
$ yarn babel-node --extensions ".ts" tools/convertSchemasToType.ts
$ /home/not/research/covid19_scenarios/node_modules/.bin/babel-node --extensions .ts tools/convertSchemasToType.ts
/home/not/research/covid19_scenarios/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/not/research/covid19_scenarios/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Makefile:12: recipe for target 'types' failed
make: *** [types] Error 1

```

## 🤔 Expected Behavior

- No error

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | Linux/ Ubuntu 18.04|
| yarn etc      | see output above|

## Related
-

**Comment by noleti** [comment]
Based on https://github.com/babel/babel/issues/11020, it seems that maybe node > 10 is required now? I am on `$ node --version v8.10.0`, which is the latest in Ubuntu 18.04
